name: Build Dependencies

on:
  workflow_call:
    secrets:
      SIC_PAT:
        required: true
      VITE_ENCRYPTION_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Clone core
        uses: actions/checkout@v6
        with:
          repository: Simple-Irc-Client/core
          token: ${{ secrets.SIC_PAT }}
          path: core

      - name: Clone network
        uses: actions/checkout@v6
        with:
          repository: Simple-Irc-Client/network
          token: ${{ secrets.SIC_PAT }}
          path: network

      - name: Build core
        working-directory: core
        env:
          VITE_ENCRYPTION_KEY: ${{ secrets.VITE_ENCRYPTION_KEY }}
        run: |
          echo "VITE_ENCRYPTION_KEY prefix: ${VITE_ENCRYPTION_KEY:0:3}..."
          rm -rf package-lock.json node_modules
          npm install
          npm run build

      - name: Build network
        working-directory: network
        env:
          ENCRYPTION_KEY: ${{ secrets.VITE_ENCRYPTION_KEY }}
        run: |
          echo "ENCRYPTION_KEY prefix: ${ENCRYPTION_KEY:0:3}..."
          rm -rf package-lock.json node_modules
          npm install
          npm run build

      - name: Prepare artifact
        run: |
          mkdir -p built-deps
          cp -r core/dist/* built-deps/
          cp network/irc-network.js built-deps/

      - name: Upload built deps
        uses: actions/upload-artifact@v6
        with:
          name: built-deps
          path: built-deps/
          if-no-files-found: error
